import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Providers from "./providers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overscroll-none`}
        suppressHydrationWarning
      >
        <main className="flex flex-col row-start-2">
          <Providers>
            <div className="flex flex-col min-h-screen w-screen px-4 gap-16 sm:px-20 font-[family-name:var(--font-geist-sans)] overscroll-x-none">
              {children}
            </div>
          </Providers>
        </main>
      </body>
    </html>
  );
}
